import { StyleSheet } from "react-native";
import { RFValue } from "react-native-responsive-fontsize";
import { hp, wp } from "../../utilis/dimensions";
const createStyles = (COLORS) =>
  StyleSheet.create({
    bg: {
      flexGrow: 1,
      backgroundColor: COLORS.bg,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      width: "100%",
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      overflow: "hidden",
      backgroundColor: COLORS.header,
      height: 80,
    },
    row: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
    },
    row111: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      width: "90%",
      // alignSelf: "center",
      marginVertical: 10,
      marginBottom: 20,
      marginLeft: wp(4),
    },
    row100: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      width: "90%",
      // alignSelf: "center",
      marginVertical: 10,
      marginBottom: 10,
    },
    icon: {
      marginHorizontal: 10,
    },
    iconMore: {
      // marginHorizontal: 10,
      alignSelf: "center",
    },
    text: {
      alignSelf: "center",
      textAlign: "left",
      height: "100%",
      // marginVertical: 10,
    },
    more: {
      textAlignVertical: "center",
      textAlign: "center",
      marginTop: -3,
      // marginVertical: 10,
    },
    text2: {
      // fontWeight: 'bold',
      marginVertical: 10,
    },

    textColored: {
      color: COLORS.blue,
      // fontWeight: 'bold',
      marginVertical: 10,
    },
    title2: {
      marginTop: hp(10),
      // fontWeight: 'bold',
    },
    title: {
      // fontWeight: 'bold',
    },
    innerContainer: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "flex-start",
      width: "90%",
    },
    innerText: {
      marginLeft: wp(1),
    },

    titlehead: {
      maxWidth: wp(50),
      maxHeight: hp(10),
    },
    addContainer: {
      // width: 50,
      // height: 50,
      borderWidth: 1,
      color: COLORS.black,
      borderColor: COLORS.blue,
      borderRadius: 20,
      paddingHorizontal: 15,
      backgroundColor: COLORS.white,
      flexDirection: "row",
    },
    btn: {
      width: "70%",
      alignSelf: "center",
      marginTop: hp(1),
      height: hp(6),
      marginBottom: hp(-1),
    },

    underlineStyleBase: {
      width: 50,
      height: 50,
      borderWidth: 1,
      color: COLORS.black,
      borderColor: COLORS.blue,
      borderRadius: 8,
      backgroundColor: "white",
    },

    underlineStyleHighLighted: {
      borderColor: COLORS.blue,
      borderRadius: 8,
    },
    otp: {
      width: "80%",
      height: 80,
      alignSelf: "center",
    },
    subContainer: {
      width: "80%",
      alignSelf: "center",
      height: "64%",
      backgroundColor: COLORS.lightGrey2,
      borderRadius: 8,
      marginVertical: 20,
      marginTop: 60,
      justifyContent: "center",
      alignItems: "center",
    },
    applicationPinSubContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },

    logo: {
      marginHorizontal: 10,
      alignSelf: "center",
      // width: 25,
      // height: 25,
    },
    keyboard: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-around",
      marginVertical: 8,
    },
    bioContainer: {
      width: "80%",
      alignSelf: "center",
      borderColor: COLORS.blue,
      borderWidth: 0,
      backgroundColor: COLORS.lightGrey2,
      borderRadius: 8,
      marginVertical: 20,
      paddingVertical: 8,
    },
    accountItem: {
      width: "90%",
      alignSelf: "center",
      alignItems: "center",
      backgroundColor: COLORS.inputBackGround3,
      // height:200,
      borderRadius: 20,
      marginVertical: 10,
      paddingBottom: 20,
    },
    description: {
      backgroundColor: COLORS.bg,
      width: "90%",
      alignSelf: "center",
      borderRadius: 10,
      padding: 10,
    },
    moreContainer: {
      alignSelf: "flex-end",
      marginTop: 20,
      marginRight: 20,
      borderWidth: 1,
      color: COLORS.black,
      borderColor: COLORS.babyBlue2,
      borderRadius: 20,
      paddingHorizontal: 5,
      // backgroundColor: COLORS.red,
      flexDirection: "row",
      justifyContent: "space-evenly",
      alignItems: "center",
      width: wp(24),
      height: hp(6),
    },

    modalView: {
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(52, 52, 52, 0.6)",
      flex: 1,
    },

    centeredView: {
      backgroundColor: COLORS.lightGrey2,
      paddingHorizontal: 5,
      borderRadius: 15,
      paddingBottom: hp(2),
      width: "90%",
      alignSelf: "center",
      // flex: 1,
    },
    centeredView2: {
      position: "absolute",

      height: hp(85),

      // alignSelf: "center",
      // top: '15%',
    },
    closeCont: {
      // marginTop: hp(1),
      alignSelf: "flex-end",
    },
    closeButton2: {
      width: "70%",
      alignSelf: "center",
      marginTop: 20,
      borderWidth: 1,
      borderColor: COLORS.grey,
    },
    centeredView3: {
      backgroundColor: COLORS.white,
      // paddingHorizontal: 5,
      borderRadius: 10,
      // paddingVertical: hp(15),
      width: wp(80),
      height: hp(65),
      marginTop: hp(10),
    },
    logo2: {
      alignSelf: "center",
      width: wp(45),
      height: hp(24),
      marginVertical: hp(3),
    },
    agreementName: {
      width: "90%",
      // marginTop: 10,
      // backgroundColor: '#8f959f',
    },
    agreementDes: {
      width: "90%",
      marginTop: 40,
      height: 150,
    },
    agreementInputDes: {
      height: 150,
      width: "95%",
      textAlignVertical: "top",
    },
    closeButton: {
      width: "70%",
      alignSelf: "center",
      marginTop: 20,
      borderWidth: 1,
      borderColor: COLORS.grey,
    },
    closeButtonTxt: {
      color: COLORS.black,
      // fontWeight: 'bold',
    },
    selectStyle: {
      width: wp(90),
      height: hp(5.5),
      backgroundColor: COLORS.inputBackGround2,
      justifyContent: "flex-start",
      alignItems: "center",
      alignSelf: "center",
      flexDirection: "row",
      marginVertical: hp(2),
      marginHorizontal: wp(8),
      borderRadius: wp(4),
    },
    selectStyleCard: {
      width: wp(70),
      height: hp(5.5),
      backgroundColor: COLORS.inputBackGround2,
      justifyContent: "flex-start",
      alignItems: "center",
      alignSelf: "center",
      flexDirection: "row",
      marginVertical: hp(2),
      marginHorizontal: wp(4),
      borderRadius: wp(6),
    },
    basicStyle2: {
      flexDirection: "row",
      width: wp(35),
      justifyContent: "center",
      alignItems: "center",
    },
    selectedStyle2: {
      flexDirection: "row",
      height: hp(5.5),
      width: wp(35),
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: COLORS.header,
      borderRadius: wp(4),
    },
    basicStyle: {
      flexDirection: "row",
      flex:1,
      justifyContent: "center",
      alignItems: "center",
    },
    selectedStyle: {
      flexDirection: "row",
      height: hp(5.5),
      flex:1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: COLORS.header,
      borderRadius: wp(4),
    },
    selectedStyleCard: {
      height: hp(5.5),
      width: wp(60),
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: COLORS.header,
      borderRadius: wp(4),
    },
    BackTxt3: {
      // fontWeight: 'bold',
      // marginHorizontal: 10,
    },
    cardItem: {
      width: "85%",
      alignSelf: "center",
      alignItems: "center",
      // height:hp(20),
      borderRadius: 10,
      marginVertical: 10,
      paddingLeft: 5,
    },
    sim: {
      width: 40,
      height: 30,
      borderRadius: 5,
    },
    cardTitle: {},
    cardSubTitle: {
      // fontWeight: 'bold'
    },
    cardBottomContainer: {
      width: "35%",
      justifyContent: "space-between",
      flexDirection: "row",
      alignItems: "center",
    },
    cardRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      width: "90%",
      alignSelf: "center",
      marginVertical: hp(0.7),
    },
    footer: {
      backgroundColor: COLORS.babyBlue4,
      padding: 3,
      borderRadius: 10,
    },
    editCon: {
      // backgroundColor: 'red',
      flexDirection: "row",
      alignItems: "center",
      height: hp(5),
      justifyContent: "space-around",
      width: wp(60),
    },
    btn2: { width: "30%", alignSelf: "center", marginTop: 20, height: hp(5) },

    //DROPdOWN
    dropdownCont: {
      alignItems: "flex-start",
    },
    dropDownRow: {
      borderBottomWidth: 1,
    },

    dropDownBtn: {
      backgroundColor: COLORS.inputBackGround,
      width: "95%",
      height: hp(6),
      // elevation: 2,
      // borderBottomColor: COLORS.bg,
      marginVertical: hp(2),
      borderWidth: wp(0.28),
      borderColor: COLORS.header,
      borderRadius: wp(2),
      // marginRight:wp(-1),
    },
    dropDownBtnTxt: {
      writingDirection: "rtl",
      textAlign: "left",
      opacity: 0.7,
      color: COLORS.black,
      fontFamily: "BahijTheSansArabic-Plain",
      fontSize: RFValue(14),
    },
    dropDownTxt: {
      textAlign: "left",
      opacity: 0.7,
      fontFamily: "BahijTheSansArabic-Plain",
      fontSize: RFValue(14),
    },
    dropDown: {
      borderColor: COLORS.white,
      maxHeight: hp(22),
      elevation: 7,
    },
  });
export default createStyles;
