import AsyncStorage from "@react-native-async-storage/async-storage";

export const BASE_URL = "https://escrow2d.meiladigital-sa.com/api/";
export const ENDPOINTS = {
  register: "register/saveRegister", //
  validateOtp: "register/validateOtp", //
  login: "login", //
  changePassword: "user/change-password", //
  forgetPassword: "password",
  validateOTPPassword: "password/verify-code",
  loadDepositMethods: "user/deposit/methods",
  createDepositRequest: "user/deposit/insert",
  confirmDepositRequest: "user/deposit/confirm?transaction=",
  depositHistory: "user/deposit/history",
  updateUserProfile: "user/profile-setting",
  getCardsPlus: "user/cards/mine",
  addCardPlus: "user/cards/submit",
  editCardPlus: "user/cards/edit",
  deleteCardPlus: "user/cards/delete",
  addCardRequest:'user/cards/get/link',
  // validatePassOTP: 'escrowUser/validateOtp',
  resetPassword: "password/reset",
  saveMpin: "escrowUser/saveMpin",
  validateMpin: "escrowUser/validateMpin",
  getHomeTransactions: "dashboard/getHomeTransactions",
  getUserDetails: "user/dashboard",
  transactionList: "user/transactions",
  transactionDetails: "user/escrow/show",
  categoryList: "user/escrow/categories",
  agreementList: "user/agreements/mine",
  addAgreement: "user/agreements/submit",
  editAgreement: "user/agreements/edit",
  saveSellerTransaction: "transaction/saveSellerTransaction",
  getTransactionTrackingStatus: "transaction/getTransactionTrackingStatus",
  uploadPicture: "escrowUser/uploadProfilePicture",
  getSettings: "settings/getSettings",
  saveSettings: "settings/saveSettings",
  updateProfile: "escrowUser/updateUserProfile",
  uploadDocument: "escrowUser/uploadDocument",
  viewDocument: "escrowUser/viewDocument",
  getNotification: "user/notifications",
  getArticles: "blogs",
  getNews: "user/in_app_notifcation",
  makeNotificationSeen: "user/notifications/seen",
  updateMPin: "escrowUser/updateMPin",
  myEscrows: "user/escrow/mine",
  withdrawList: "user/withdraw/history",
  withdrawMethods: "user/withdraw/methods",
  withdrawRequest: "user/withdraw/store",
  withdrawConfirm: "user/withdraw/confirm",
  cancleEscrowByBuyerOrSeller: "user/escrow/cancel",
  acceptEscrowByBuyer: "user/escrow/accept",
  deleteAgreement: "user/agreements/delete",
  KYCDynamicForm: "user/kyc/form",
  submitKYCform: "user/kyc/create",
  checkCoupon: "user/coupon/check",
  generalSettings: "general-setting",
  ticketsList: "user/support/mine",
  newSupportTicket: "user/support/create",
  ticketDetails: "user/support/details",
  closeTicket: "user/support/close",
  ticketReply: "user/support/reply",
  statusList: "user/escrow/status_value",
  checkPassword: "user/check/password",
  changeEmailOrPhone: "user/change/eom/send/code",
  verifyEmail: "user/verify-email",
  verifyCode: "user/change/eom/verify/code",
  verifySMS: "user/verify-sms",
  citiesWithStates: "get_cities",
  analyticsByYear:"user/analysis/sey",
  analyticsByCatYear:"user/analysis/scey",
  analyticsByMonth:"user/analysis/sem",
  analyticsByCatMonth:"user/analysis/scem",
 contactUs: "contact_us",
 reportMessage:"user/message/report_message",
 blockUserRequest:"user/message/block_user_request",
 escrowStatusValue: "user/escrow/status_value",

};
export const getBaseURL = async () => {
  let env = await AsyncStorage.getItem("ENVIROMENT");
  return env && env == "1"
    ? "https://idhmn.com/backend/api/"
    : "https://escrow2d.meiladigital-sa.com/backend/api/";
};
export const ENDPOINTS2 = {
  register: "api/register",
  verifyEmail: "api/user/verify-email",
  verifySMS: "api/user/verify-sms",
  sendVerificationEmail: "api/user/send-resend-verify?type=email",
  sendVerificationSms: "api/user/send-resend-verify?type=sms",
  addToken: "device/fcm",
  getMessages: "user/message/getmessages",
  reply: "user/message/reply",
  getBanks: "user/bankaccounts/mine",
  addBank: "user/bankaccounts/submit",
  editBank: "user/bankaccounts/edit",
  deleteBank: "user/bankaccounts/delete",
  addNewEscrow: "user/escrow/addnew",
  otp_login: "otp_login",
  buyerRejectDelivery: "user/escrow/reject_delivery",
  getKey: "user/google/getkey",
  enableGoogle: "user/google/enable",
  disableGoogle: "user/google/disable",
  verifyFA: "user/google/verify-g2fa",
  verifyFastSignIn: "2fa_login",
  payEscrow: "user/escrow/pay",
  payEscrowMoyasar: "user/escrow/pay/moyasar",
  sellerAccept: "user/escrow/accept",
  escrowPlusReview: "user/escrow/review",
  sellerDelivery: "user/escrow/delivered",
  raiseDispute: "user/escrow/dispute",
  buyerDispatch: "user/escrow/dispatch",
  sellerAcceptReject: "user/escrow/accept_reject_delivery",
  pinStatus: "user/mpin/status",
  add_updatePin: "user/mpin",
  checkPin: "user/mpin/check",
  resetpin: "user/mpin-reset?type=",
  resetpinCheck: "user/mpin-reset-check",
  resetchangepin: "user/mpin-reset-change",
  changeLanguage: "user/user-language",
  escrowCalculation: "user/escrow/front-calculation",
  acceptAfterPay: "user/escrow/accept_after_pay",
  faq: "faq",
  banned_products: "banned_products",
  ratingCheck: "app_review/check",
  ratingAdd: "app_review",
  submitShortEscrow: "user/escrow/addnew/short",
  updateShortDraft: "user/escrow/update_draft",
  delivery_confirm: "user/escrow/delivery_confirm",
  previewAgreementShortEscrow: "user/escrow/short_agreement",
  getChargeAPI: "user/escrow/front_charge",
  createShortDraft: "user/escrow/addnew/short/draft",
  makeDraftLive: "user/escrow/update_to_live",
  signOut: "user/token/forget",
  submitPhoneRegister: "register_otp",
  verifyMobileRegister: "register_otp_confirm",
  startChatBot:'chatbot/start',
  chatBotReply:'chatbot/reply',
  checkCountry:'check/country'
};
export const getBaseURL2 = async () => {
  let env = await AsyncStorage.getItem("ENVIROMENT");

  return env && env == "1"
    ? "https://idhmn.com/backend/"
    : "https://escrow2d.meiladigital-sa.com/backend/";
};
